### ISSUE TITLE
When editing a ScannedBook work Editors can modify metadata

### ISSUE THREAD

**Issue by flyingzumwalt** [pulibrary/pul-worthwhile#13]
When editing a ScannedBook work I can
- [x] upload files
- [x] change the voyager ID or EAD id
- [x] change the “portion note”
- [x] change the description

also see #14 and #15

**Comment by eliotjordan** [comment]
@flyingzumwalt We are having problems with the [scanned book feature tests](https://github.com/pulibrary/pul-worthwhile/blob/edit_scanned_book/spec/features/scanned_books_controller_spec.rb#L12-L27).  Login is working, and the user can visit the first page in each spec. After follow a link or button, however, the authorization is no longer valid. Any ideas?

**Comment by eliotjordan** [comment]
![bush](https://cloud.githubusercontent.com/assets/784196/7306956/08a2a3a0-e9d7-11e4-9ec8-6a44ecdac1e6.jpg)
