### ISSUE TITLE
Identify objects with NOIDs

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pul-worthwhile#23]
New objects (CurationConcerns) should have a NOID. See https://github.com/projecthydra-labs/active_fedora-noid.

**Comment by kevinreiss** [comment]
Added the basic setup for this 3d19169c3f85d0438e20f5fb6c2bf7d6f89a487c. @jpstroop Do you want to keep the namespace construct we used in pul-store? https://github.com/pulibrary/pul-store/blob/3bbd3b9702ca759557935986eced843b26432257/lib/pul_store/id_service.rb
If yes it is just a matter of implementing a simple custom minter class per the gem's readme file.
