### ISSUE TITLE
When a contributor inputs an EAD ID it populates the appropriate fields

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul-worthwhile#3]
Related to #1. 

When a contributor inputs an EAD component ID into the create or edit screen it populates or refreshes the following data fields.
- [ ] Makes sure this a valid EAD ID. 
- [ ] Fills in Title
- [ ] Fills in Date
- [ ] Fills in ?

Sample URI: http://findingaids.princeton.edu/collections/AC123/c00004.xml?scope=record

**Comment by kevinreiss** [comment]
@jpstroop , any recommendations on the mapping here?

**Comment by jpstroop** [comment]
If/when there is a framework in place for this functionality (get data,
populate properties, persist XML source), why don't you close this issue
and open a separate one for tweaking the mapping?

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by kevinreiss** [comment]
Okay. I opened that under #25.

**Comment by kevinreiss** [comment]
Closing per Jon's suggestion.
