### ISSUE TITLE
Retrieve descriptive metadata and mint ARK when a ScannedBook is created on the server

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pul-worthwhile#9]
- [x] Retrieve the metadata from Voyager (bibdata) when ID fits the pattern of that system (see #2)
- [x] Retrieve the metadata from the EAD system (pulfa) when ID fits the pattern of that system (see #3)
- [x] Store the metadata in its native format (MARCXML or expanded EAD)
- [x] Extract essential metadata from the record (title, creator, publisher, date) and stores it semantic fields (dc:title, dc:creator, etc.)
- [ ] Mint an ARK for the work - see https://github.com/duke-libraries/ezid-client for interface for ARC

**Comment by kevinreiss** [comment]
Example PULFA: 
ID: AC123_c00004
URL http://findingaids.princeton.edu/collections/AC123/c00004.xml?scope=record
Example Voyager: 
ID: 2028405
URL: http://bibdata.princeton.edu/bibliographic/2028405

**Comment by kevinreiss** [comment]
Using `src_metadata` as the property name throws an unacceptable property name error:

```
.../gems/active_fedora-9d7317d5596d/lib/active_fedora/attributes.rb:176:in `property': src_metadata is a keyword and not an acceptable property name. (ArgumentError)
  from /Users/kevinreiss/Projects/hydra/pul-worthwhile/app/models/scanned_book.rb:13:in `<class:ScannedBook>'
  from /Users/kevinreiss/Projects/hydra/pul-worthwhile/app/models/scanned_book.rb:3:in `<top (required)>'
```

Changed it to `src_system_metadata`. Will that work okay? Maybe we should just spell out source.

**Comment by kevinreiss** [comment]
Odd NoMethod error on code extracted from pul-store for parsing Marc.

```
1) ScannedBook With a Voyager ID Gets data from Voyager
     Failure/Error: subject.apply_external_metadata
     NoMethodError:
       private method `format' called for #<MARC::DataField:0x007f960a3fa460>
     # ./app/models/concerns/pul_store/external_metadata_source.rb:298:in `title_from_marc'
     # ./app/models/scanned_book.rb:38:in `apply_bibdata'
     # ./app/models/scanned_book.rb:72:in `apply_external_metadata'
     # ./spec/models/scanned_book_spec.rb:120:in `block (3 levels) in <top (required)>'
```
